GET http://127.0.0.1:8000/health
Accept: application/json

###

GET http://127.0.0.1:8000/api/projects
Accept: application/json

###

GET http://127.0.0.1:8000/api/projects/10189
Accept: application/json
